version: '3'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'

  website:
    build: .
    command: supervisord -n
    environment:
      ENV: 'dev'
      URL: 'http://suite.local:8000'
      SERVER_NAME: 'suite.local:8000'
      SQLALCHEMY_DATABASE_URI: "mysql://root:bacon@mysqlserver/dev"
      REDIS_HOST: redis
    volumes:
      - '.:/src'
    ports:
      - '8000:80'
    links:
      - 'db:mysqlserver'
      - redis
    hostname: suite

  db:
    hostname: mysqlserver
    ports:
      - '3306:3306'
    image: mysql:5.7
    command: '--sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    environment:
        MYSQL_ROOT_PASSWORD: bacon
        MYSQL_DATABASE: dev
